# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class AddressEntry(BaseModel):
    street: typing.Optional[str] = Field(default=None, description='Street address line 1. Null if not on card.')
    street2: typing.Optional[str] = Field(default=None, description='Suite, unit, floor, etc. Null if not on card.')
    city: typing.Optional[str] = Field(default=None, description='City. Null if not on card.')
    state: typing.Optional[str] = Field(default=None, description='State or province. Null if not on card.')
    postal_code: typing.Optional[str] = Field(default=None, description='ZIP or postal code. Null if not on card.')
    country: typing.Optional[str] = Field(default=None, description='Country. Null if not on card.')

class BusinessCard(BaseModel):
    validationStatus: typing.Optional[types.ValidationStatus] = Field(default=None, description='VALID = image is a business card AND text is readable (with effort, blur, low light, etc.). NOT_A_BUSINESS_CARD = image is not a business card (puppy, landscape, receipt, generic document, etc.). ILLEGIBLE = image is or appears to be a business card BUT text cannot be recovered even with best vision effort.')
    validationMessage: typing.Optional[str] = Field(default=None, description='If validationStatus is NOT_A_BUSINESS_CARD: brief description of what the image actually is (e.g., \'a photo of a dog\', \'a restaurant receipt\'). If ILLEGIBLE: brief reason (e.g., \'image is too blurry to read\', \'glare obscures most text\', \'resolution is too low\'). If VALID: empty string.')
    full_name: typing.Optional[str] = Field(default=None, description='Full name as printed. Null if absent.')
    first_name: typing.Optional[str] = Field(default=None, description='First name only if unambiguously separable. Null otherwise.')
    last_name: typing.Optional[str] = Field(default=None, description='Last name only if unambiguously separable. Null otherwise.')
    prefix: typing.Optional[str] = Field(default=None, description='Name prefix (Dr., Prof.). Null if absent.')
    suffix: typing.Optional[str] = Field(default=None, description='Name suffix (Jr., MD, PhD). Null if absent.')
    title: typing.Optional[str] = Field(default=None, description='Job title exactly as printed. Null if absent.')
    organization: typing.Optional[str] = Field(default=None, description='Company or organization exactly as printed. Null if absent.')
    department: typing.Optional[str] = Field(default=None, description='Department or division. Null if absent.')
    phones: typing.List["PhoneEntry"] = Field(description='All phones on the card. Empty array if none.')
    emails: typing.List["EmailEntry"] = Field(description='All emails on the card. Empty array if none.')
    urls: typing.List[str] = Field(description='All website URLs on the card, exactly as printed. Empty array if none.')
    address: typing.Optional["AddressEntry"] = Field(default=None, description='Mailing/business address if printed. Null if no address present.')
    linkedin: typing.Optional[str] = Field(default=None, description='LinkedIn URL or handle if printed. Null if absent.')
    twitter: typing.Optional[str] = Field(default=None, description='Twitter/X handle or URL if printed. Null if absent.')
    instagram: typing.Optional[str] = Field(default=None, description='Instagram handle or URL if printed. Null if absent.')
    note: typing.Optional[str] = Field(default=None, description='Any other text on the card not covered above. Null if nothing extra.')

class EmailEntry(BaseModel):
    address: typing.Optional[str] = Field(default=None, description='Email address exactly as printed on the card.')
    type: typing.Optional[types.EmailType] = Field(default=None, description='Type of email. If unlabeled on a business card, default to WORK.')

class PhoneEntry(BaseModel):
    number: typing.Optional[str] = Field(default=None, description='Phone number exactly as printed on the card. Preserve formatting (dashes, parens, country codes).')
    type: typing.Optional[types.PhoneType] = Field(default=None, description='Type of phone. If labeled (M:, Cell:, Fax:, F:, Work:), use the matching type. If unlabeled on a business card, default to WORK.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
