# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (3)
# #########################################################################

class EmailType(str, Enum):
    WORK = "WORK"
    PERSONAL = "PERSONAL"
    OTHER = "OTHER"

class PhoneType(str, Enum):
    MOBILE = "MOBILE"
    WORK = "WORK"
    HOME = "HOME"
    FAX = "FAX"
    OTHER = "OTHER"

class ValidationStatus(str, Enum):
    VALID = "VALID"
    NOT_A_BUSINESS_CARD = "NOT_A_BUSINESS_CARD"
    ILLEGIBLE = "ILLEGIBLE"

# #########################################################################
# Generated classes (4)
# #########################################################################

class AddressEntry(BaseModel):
    street: typing.Optional[str] = Field(default=None, description='Street address line 1. Null if not on card.')
    street2: typing.Optional[str] = Field(default=None, description='Suite, unit, floor, etc. Null if not on card.')
    city: typing.Optional[str] = Field(default=None, description='City. Null if not on card.')
    state: typing.Optional[str] = Field(default=None, description='State or province. Null if not on card.')
    postal_code: typing.Optional[str] = Field(default=None, description='ZIP or postal code. Null if not on card.')
    country: typing.Optional[str] = Field(default=None, description='Country. Null if not on card.')

class BusinessCard(BaseModel):
    validationStatus: ValidationStatus = Field(description='VALID = image is a business card AND text is readable (with effort, blur, low light, etc.). NOT_A_BUSINESS_CARD = image is not a business card (puppy, landscape, receipt, generic document, etc.). ILLEGIBLE = image is or appears to be a business card BUT text cannot be recovered even with best vision effort.')
    validationMessage: str = Field(description='If validationStatus is NOT_A_BUSINESS_CARD: brief description of what the image actually is (e.g., \'a photo of a dog\', \'a restaurant receipt\'). If ILLEGIBLE: brief reason (e.g., \'image is too blurry to read\', \'glare obscures most text\', \'resolution is too low\'). If VALID: empty string.')
    full_name: typing.Optional[str] = Field(default=None, description='Full name as printed. Null if absent.')
    first_name: typing.Optional[str] = Field(default=None, description='First name only if unambiguously separable. Null otherwise.')
    last_name: typing.Optional[str] = Field(default=None, description='Last name only if unambiguously separable. Null otherwise.')
    prefix: typing.Optional[str] = Field(default=None, description='Name prefix (Dr., Prof.). Null if absent.')
    suffix: typing.Optional[str] = Field(default=None, description='Name suffix (Jr., MD, PhD). Null if absent.')
    title: typing.Optional[str] = Field(default=None, description='Job title exactly as printed. Null if absent.')
    organization: typing.Optional[str] = Field(default=None, description='Company or organization exactly as printed. Null if absent.')
    department: typing.Optional[str] = Field(default=None, description='Department or division. Null if absent.')
    phones: typing.List["PhoneEntry"] = Field(description='All phones on the card. Empty array if none.')
    emails: typing.List["EmailEntry"] = Field(description='All emails on the card. Empty array if none.')
    urls: typing.List[str] = Field(description='All website URLs on the card, exactly as printed. Empty array if none.')
    address: typing.Optional["AddressEntry"] = Field(default=None, description='Mailing/business address if printed. Null if no address present.')
    linkedin: typing.Optional[str] = Field(default=None, description='LinkedIn URL or handle if printed. Null if absent.')
    twitter: typing.Optional[str] = Field(default=None, description='Twitter/X handle or URL if printed. Null if absent.')
    instagram: typing.Optional[str] = Field(default=None, description='Instagram handle or URL if printed. Null if absent.')
    note: typing.Optional[str] = Field(default=None, description='Any other text on the card not covered above. Null if nothing extra.')

class EmailEntry(BaseModel):
    address: str = Field(description='Email address exactly as printed on the card.')
    type: EmailType = Field(description='Type of email. If unlabeled on a business card, default to WORK.')

class PhoneEntry(BaseModel):
    number: str = Field(description='Phone number exactly as printed on the card. Preserve formatting (dashes, parens, country codes).')
    type: PhoneType = Field(description='Type of phone. If labeled (M:, Cell:, Fax:, F:, Work:), use the matching type. If unlabeled on a business card, default to WORK.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
