# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AddressEntry": types.AddressEntry,
    "stream_types.AddressEntry": stream_types.AddressEntry,

    "types.BusinessCard": types.BusinessCard,
    "stream_types.BusinessCard": stream_types.BusinessCard,

    "types.EmailEntry": types.EmailEntry,
    "stream_types.EmailEntry": stream_types.EmailEntry,

    "types.PhoneEntry": types.PhoneEntry,
    "stream_types.PhoneEntry": stream_types.PhoneEntry,


    "types.EmailType": types.EmailType,

    "types.PhoneType": types.PhoneType,

    "types.ValidationStatus": types.ValidationStatus,

}